name: CI
on:

  push:

    branches:

      - main
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  # CSV_URL: "daTA.csv"

  TARGET_VAR: "quality"
  ALPHA: 0.8
  L1_RATIO: 0.9
  RANDOM_STATE: 42
  EXPERIMENT_NAME: "Default"
  RUN_NAME: "salty-donkey-31"
  MLFLOW_TRACKING_URI: "https://0164-2405-201-6013-8ba4-80fe-9734-a413-68bf.in.ngrok.io"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: "dts-mlops-bucket"
  S3_FOLDER_NAME: "model-registry"
  MODEL_NAME: "Model-2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
# Setup Python 3.9

      - name: Set up Python 3.9
        uses: actions/setup-python@v4

        with:
          python-version: "3.9"
# Check Env Variables

      - name: Check Env
        run: |
          echo $CSV_URL
# Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install boto3
# #Run as a mlflow project.

      # - name: Run mlflow project

      #   run: |

      #     mlflow run wine_example --env-manager=local


      #run python deploy_model file

      - name: Run python deploy.py

        run: python deploy.py --env-manager=local